name: tourism
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^16.3.0
  table_calendar: ^3.0.9
  fl_chart: ^0.66.0
  provider: ^6.1.1

  cupertino_icons: ^1.0.8

  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  http: ^1.1.0
  google_sign_in: ^6.1.5
  modal_progress_hud_nsn: ^0.5.1
  js: ^0.6.7
  intl: ^0.20.2
  image_picker: ^1.0.4
  firebase_storage: ^11.6.5
  material_design_icons_flutter: ^7.0.7296
  timeago: ^3.7.1
  timeago_flutter: ^3.7.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
